from app.ontology.sedo import get_sedo

sedo = get_sedo()


def test_ontology_is_sizable_and_bilingual():
    # Generated by tools/build_sedo.py; should approach the paper's ~200 concepts (§V-D).
    assert len(sedo.nodes) >= 150
    parent_layers = ("technical_stack", "domain_entity", "methodology", "task_type")
    groups = [c for c in sedo.nodes.values() if c["parent"] in parent_layers]
    assert len(groups) >= 20                       # top-level parent classes across the four layers
    # Bilingual coverage: a Vietnamese surface form maps onto the same concept as its English name.
    assert "hotel" in sedo.recognize("hệ thống quản lý khách sạn")


def test_depths():
    assert sedo.depth("thing") == 1
    assert sedo.depth("frontend") == 3
    assert sedo.depth("react") == 4


def test_wu_palmer_examples():
    assert sedo.wu_palmer("react", "angular") == 0.75   # same Frontend group (paper Sect 3.3)
    assert sedo.wu_palmer("react", "django") == 0.5      # different group, same layer
    assert sedo.wu_palmer("react", "hotel") == 0.25      # different layer, LCS = root
    assert sedo.wu_palmer("react", "react") == 1.0


def test_wpath_examples():
    # Cross-group domains score low (paper Sect 5.4: S_dom ~ 0.2).
    assert abs(sedo.wpath("hotel", "pharmacy") - 0.205) < 0.02
    # Siblings score higher than a cross-group pair.
    assert sedo.wpath("hotel", "restaurant") > sedo.wpath("hotel", "pharmacy")
    assert sedo.wpath("hotel", "hotel") == 1.0


def test_recognize():
    ids = sedo.recognize("A hotel booking system built with React and PostgreSQL")
    assert "react" in ids
    assert "postgresql" in ids
    assert "hotel" in ids


def test_recognize_coverage_gap():
    # Paper Sect 5.5: technologies phrased outside the vocabulary are missed.
    assert sedo.recognize("uses Microsoft SQL") == frozenset()


def test_set_similarity_empty_returns_none():
    assert sedo.set_similarity(set(), {"react"}, sedo.wu_palmer) is None
